name: build

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  msrv:
    name: Build on minimal supported rust
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust 1.75
        run: |
          rustup override set 1.75
          rustup update 1.75
          rustc --version

      - name: Build with default feature
        run: cargo build

      - name: Build with tokio feature
        run: cargo build --features tokio_socket

      - name: Build with smol_socket feature
        run: cargo build --features smol_socket
